name: Event Contract CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:

jobs:

  build_and_test:
    name: build_and_test
    uses: projectronin/github/.github/workflows/event_contract_cicd.yaml@event_contract_cicd
    with:
      schema_name: ronin-contract-event-template
      publish: ${{ github.ref == 'refs/heads/main' }}
    
