name: Event Contract CI/CD

on:
  push:
    branches:
      - main
      - v*
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: test and build
        uses: projectronin/github/.github/actions/json_contract_cicd_gradle.yaml@feature/update-event-workflow-to-gradle
