name: Event Contract CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build_and_test:
    name: build_and_test
    uses: projectronin/github/.github/workflows/event_contract_cicd.yaml@feature/update-event-workflow-to-gradle
    secrets:
      docker_username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      docker_password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}
      nexus_user:      ${{ secrets.NEXUS_RAW_USER }}
      nexus_token:     ${{ secrets.NEXUS_RAW_TOKEN }}
